
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 20 12:41:43 CST 2017
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int C_par = 24;
  public static final int Tabu = 16;
  public static final int O_Bra = 29;
  public static final int Cero_Mas = 10;
  public static final int Retorno = 25;
  public static final int C_doble = 15;
  public static final int Uno_Mas = 11;
  public static final int Identificador = 3;
  public static final int Uno_Cero = 12;
  public static final int Coma = 28;
  public static final int R_reserv = 18;
  public static final int O_par = 23;
  public static final int Salto = 13;
  public static final int C_simple = 14;
  public static final int Err = 31;
  public static final int Col = 22;
  public static final int Cadena = 19;
  public static final int Conj = 26;
  public static final int EOF = 0;
  public static final int Todo = 17;
  public static final int Row = 21;
  public static final int P_Coma = 6;
  public static final int Flecha = 5;
  public static final int error = 1;
  public static final int Conc = 9;
  public static final int C_Bra = 30;
  public static final int Text = 20;
  public static final int Disy = 8;
  public static final int Doble_por = 7;
  public static final int Letra = 2;
  public static final int DosPt = 27;
  public static final int Caracter = 4;
}

